### ISSUE TITLE
Interpreting output results and plotting pileups

### ISSUE THREAD

**Issue by wilsoner2175** [ysora/stripenn#20]
Hi,

Thank you so much for creating such a useful tool! I have a few questions. 1) When I'm looking at the 4 positions in the result file from stripenn compute, I'm wondering which positions to use for the bed file that makes the pileup plots. I've been using positions 1 and 4 as they seem to represent the span of the stripe. 2) I'm also interested in intersecting stripes with boundary annotations--similarly, I'm wondering which positions I would use to identify overlaps of stripes with a CTCF binding site coordinate. 

Here is an example of the stripes pileup plot that I'm generating from (using pos1 and pos4 in the bed file):
coolpup.py $COOL $CD34_stripes_BED --outname $CD34_stripes_BED_OUT --local --rescale --rescale_flank 1 --rescale_size 99
plotpup.py --input_pups $CD34_stripes_BED_OUT --output CD34_striptes.pileup.pdf 

<img width="487" alt="Screenshot 2024-01-15 at 3 09 03 PM" src="https://github.com/ysora/stripenn/assets/53955326/a5a877b4-1600-4d24-a2c3-21551063c453">

**Comment by ysora** [comment]
Hi,

Thanks for your interest in Stripenn!
To draw a pileup plot, you need to create bed file using pos3 (start of stripe) and pos4 (end of stripe).
Similarly, you can use pos3 and pos4 to make intersection of stripe with CTCF binding site coordinate.
Thanks,

Sora
________________________________
From: wilsoner2175 ***@***.***>
Sent: Monday, January 15, 2024 4:10 PM
To: ysora/stripenn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ysora/stripenn] Interpreting output results and plotting pileups (Issue #20)


Hi,

Thank you so much for creating such a useful tool! I have a few questions. 1) When I'm looking at the 4 positions in the result file from stripenn calculate, I'm wondering which positions to use for the bed file that makes the pileup plots. I'm also interested in intersecting stripes with boundary annotations--similarly, I'm wondering which positions I would use to identify overlaps of stripes with a CTCF binding site coordinate.

Here is an example of the stripes file that I'm generating from
coolpup.py $COOL $CD34_stripes_BED --outname $CD34_stripes_BED_OUT --local --rescale --rescale_flank 1 --rescale_size 99
plotpup.py --input_pups $CD34_stripes_BED_OUT --output CD34_striptes.pileup.pdf

**Comment by wilsoner2175** [comment]
Thank you so much for your response! I'm wondering if using pos1 and 2 makes sense for intersecting with CTCF binding sites. I'm looking specifically for boundaries that may be compromised by the lack of CTCF binding in my samples. Using the full stripe coordinates feels like I'm not looking in a specific enough region. Do pos1 and 2 correspond to the so-to-speak "anchor" of the stripe?

**Comment by ysora** [comment]
Oh I see your point.
There is no specific definition of stripe anchor, but we can treat the root of stripe as an anchor. There are two types of stripes. One is downward stripe where pos1 and pos3 are same. For these stripes, you can take pos1 and give some appropriate padding (eg 50kb) to get the anchor coordinate. The other is upward stripe where pos2 and pos4 are same. For these stripes, you can take pos2 and give some padding
THANKS

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________
From: wilsoner2175 ***@***.***>
Sent: Tuesday, January 16, 2024 11:54:41 AM
To: ysora/stripenn ***@***.***>
Cc: Yoon, Sora ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ysora/stripenn] Interpreting output results and plotting pileups (Issue #20)


Thank you so much for your response! I'm wondering if using pos1 and 2 makes sense for intersecting with CTCF binding sites. I'm looking specifically for boundaries that may be compromised by the lack of CTCF binding in my samples. Using the full stripe coordinates feels like I'm not looking in a specific enough region. Do pos1 and 2 correspond to the so-to-speak "anchor" of the stripe?

**Comment by wilsoner2175** [comment]
That makes sense, I will use that approach! Thank you again for your input and feedback, it is much appreciated!

Ellie
