### ISSUE TITLE
How to run stripenn

### ISSUE THREAD

**Issue by Jason-Qiuhai** [ysora/stripenn#7]
Hi,

This may be a silly question. After I run 'pip install stripenn', how do I run the stripenn in the command line? Isn't stripenn a python package? Shouldn't I import stripenn in my python script? Thanks in advance for any suggestion.

**Comment by ysora** [comment]
Stripenn is command line interface (CLI) program. After installation, you can type following on the terminal to run it with example data:

cd <Test_Directory> # Move to your test directory
wget https://www.dropbox.com/s/1bb2npvrzp3by5y/BL6.DPT.chr16.mcool?dl=0 -O test.mcool --no-check-certificate
stripenn compute --cool test.mcool::resolutions/5000 --out output_dir/ -k 16 -m 0.95,0.96,0.97,0.98,0.99 -n 1

Thanks!

Sora

**Comment by Jason-Qiuhai** [comment]
> Stripenn is command line interface (CLI) program. After installation, you can type following on the terminal to run it with example data:
> 
> cd <Test_Directory> # Move to your test directory wget https://www.dropbox.com/s/1bb2npvrzp3by5y/BL6.DPT.chr16.mcool?dl=0 -O test.mcool --no-check-certificate stripenn compute --cool test.mcool::resolutions/5000 --out output_dir/ -k 16 -m 0.95,0.96,0.97,0.98,0.99 -n 1
> 
> Thanks!
> 
> Sora

Thanks for the quick reply. I could run stripenn now, but I got an error while calculating stripiness. Do you know how to handle this?

5. Stripiness calculation ...
  0%|                                                  | 0/1113 [00:00<?, ?it/s]/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1216: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/src/getStripe.py", line 735, in iterate_idx
    center = np.delete(center, rowdel, axis=0)
  File "<__array_function__ internals>", line 180, in delete
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5128, in delete
    keep[obj,] = False
IndexError: index -26 is out of bounds for axis 0 with size 24

**Comment by ysora** [comment]
Did you get this error with example data? or your own data?
If you used your own data, can I repeat stripenn running with your data for finding the reason??
Thanks,

Sora

**Comment by Jason-Qiuhai** [comment]
> Did you get this error with example data? or your own data? If you used your own data, can I repeat stripenn running with your data for finding the reason?? Thanks,
> 
> Sora

I got the error with my own data. It would be great if you could run with my data. The data I used was 4DNFI2TK7L2F.hic downloaded from https://data.4dnucleome.org/files-processed/4DNFI2TK7L2F/. I used hic2cool to transform the data into .cool format. I only used 1000 resolution. I can send you an email sharing my processed data if you can share with me your email address. Thanks. 

Best,
Qiuhai

**Comment by ysora** [comment]
Stripenn is optimized for 10k or 5k resolution. I will also test it for 1k resolution data. During that, could you run the program with 5k resolution data?? 
Thanks.

Sora

**Comment by Jason-Qiuhai** [comment]
> Stripenn is optimized for 10k or 5k resolution. I will also test it for 1k resolution data. During that, could you run the program with 5k resolution data?? Thanks.
> 
> Sora

Sure, I will try 5k resolution data. Thanks.

Qiuhai
