### ISSUE TITLE
Can you share your code of doing pileup plot?

### ISSUE THREAD

**Issue by Jason-Qiuhai** [ysora/stripenn#8]
Hi Sora,

I'm wondering if you could share your code of doing the pileup plot to get this picture.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/71804132/197917418-f59181e2-9061-427a-b11c-c918c24103a8.png">

I know in your paper there is a paragraph saying
<img width="445" alt="image" src="https://user-images.githubusercontent.com/71804132/197917471-ce69327e-2bf1-4b7d-8224-8551c2d6007b.png">

But I cannot understand how to reproduce it. I also consulted with the first author of coolpup.py and still could not understand the details. I really appreciate any help. My email is qjz5084@psu.edu if needed.

Thank,
Qiuhai

**Comment by ysora** [comment]
Please refer to this page: https://github.com/VahediLab/stripenn-data-code/tree/master/Figure1
The bed files are stored in the Data folder.
Thanks.

Sora

**Comment by Jason-Qiuhai** [comment]
> Please refer to this page: https://github.com/VahediLab/stripenn-data-code/tree/master/Figure1 The bed files are stored in the Data folder. Thanks.
> 
> Sora

Thanks for sharing the link. I have a question regarding the data format. The output of Stripenn is in chrom1, pos1, pos2, chrom2, pos3, pos4, but the input of coolpup.py has the format of chrom1, pos1, pos2. Can you tell me how you process the output of Stripenn to get the input of coolpup.py? Thanks!

Best,
Qiuhai

**Comment by ysora** [comment]
![image](https://user-images.githubusercontent.com/7501350/198126839-67b21c5f-2b8e-4a21-9c14-ffc4a66c37ef.png)
I just took pos3 and pos4 of stripenn output as the pos1 and pos2 of the input bed file.
Thanks!

Sora
