### ISSUE TITLE
Stripenn score 

### ISSUE THREAD

**Issue by Jason-Qiuhai** [ysora/stripenn#9]
Hi Sora,

I am running the Stripenn score function. Here is my code

stripenn compute --cool 4DNFI2TK7L2F.cool --out output_dir/ -k 22 -m 0.95,0.96,0.97,0.98,0.99 -s 
stripenn score --cool 4DNFI2TK7L2F.cool -c ./output_dir/result_filtered.tsv -n 4 -o stripiness

I know that stripiness is already calculated in the result_filtered.tsv file. I was trying to compute the stripiness using the score function. The compute function ran smoothly, but when I ran score function, I got the error (I removed the headers of result_filtered.tsv)
<img width="947" alt="image" src="https://user-images.githubusercontent.com/71804132/198182654-bbde4460-d0fd-4650-bdef-bc7a59010a6b.png">

Can you tell me how to deal with it? Thanks.

Best,
Qiuhai

**Comment by ysora** [comment]
Could you send me your  **./output_dir/result_filtered.tsv** through my email? (sora.yoon@pennmedicine.upenn.edu)
Let me test that!

Thanks,

Sora

**Comment by Jason-Qiuhai** [comment]
Hi Sora,

Thanks for working with the data. The score function is working for the output of stripenn compute. I have a question regarding the score function. Right now I have some stripes (saved in chr22_5000.stripe) like this
<img width="484" alt="image" src="https://user-images.githubusercontent.com/71804132/200140698-997c1a10-6063-4cca-8179-285418ffed24.png">

When I run 
stripenn score --cool ./stripe_res/4DNFI2TK7L2F.cool -c chr22_5000.stripe -o stripiness.stripe -n 4

I got the error message
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/71804132/200140745-87d009d8-1326-4d02-88f8-e44017c6468f.png">

Can you tell me what is wrong here? Thanks!

Best,
Qiuhai

**Comment by ysora** [comment]
Could you try score function with a parameter -n 1 ?
I couldn't fix parallel programming issue yet.
Thanks,

Sora

________________________________
From: Jason-Qiuhai ***@***.***>
Sent: Saturday, November 5, 2022, 4:50 PM
To: ysora/stripenn ***@***.***>
Cc: Yoon, Sora ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ysora/stripenn] Stripenn score  (Issue #9)


Hi Sora,

Thanks for working with the data. The score function is working for the output of stripenn compute. I have a question regarding the score function. Right now I have some stripes (saved in chr22_5000.stripe) like this
[image]<https://user-images.githubusercontent.com/71804132/200140698-997c1a10-6063-4cca-8179-285418ffed24.png>

When I run
stripenn score --cool ./stripe_res/4DNFI2TK7L2F.cool -c chr22_5000.stripe -o stripiness.stripe -n 4

I got the error message
[image]<https://user-images.githubusercontent.com/71804132/200140745-87d009d8-1326-4d02-88f8-e44017c6468f.png>

Can you tell me what is wrong here? Thanks!

Best,
Qiuhai

**Comment by Jason-Qiuhai** [comment]
Hi Sora,

Thanks for the quick reply. I tried -n 1, but still got this error message. Do you have any idea what is wrong?
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/71804132/200141831-96826a9e-7270-4a06-880b-10f27f5caa51.png">

Thanks,
Qiuhai

**Comment by ysora** [comment]
I am not sure. Could you send me your coordinates data for the test?
Thanks.

Sora

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jason-Qiuhai ***@***.***>
Sent: Saturday, November 5, 2022 5:23:23 PM
To: ysora/stripenn ***@***.***>
Cc: Yoon, Sora ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ysora/stripenn] Stripenn score (Issue #9)


Hi Sora,

Thanks for the quick reply. I tried -n 1, but still got this error message. Do you have any idea what is wrong?
[image]<https://user-images.githubusercontent.com/71804132/200141831-96826a9e-7270-4a06-880b-10f27f5caa51.png>

Thanks,
Qiuhai

**Comment by Jason-Qiuhai** [comment]
Hi Sora,

Two quick questions. 
1. What is the starting point of each chromosome in your output? Is it 1? 
2. Suppose the output (under 5kb) is 
22	48475001	48500000	22	47775001	48500000
Is the stripe region the square formed by two points (48475001, 47775001) and (48500000, 48500000). Or (48475001, 47775001) and (48505000, 48505000)?

Thanks,
Qiuhai

**Comment by ysora** [comment]
Hi Qiuhai,


  1.  Yes, the chromosome starts from 1.

  1.  The first one is correct. Hope this figure will help your understanding.
[cid:50017761-85f5-4c8b-b3fb-b1ed83c62a68]

Thanks,

Sora
________________________________
From: Jason-Qiuhai ***@***.***>
Sent: Friday, November 11, 2022 10:50 AM
To: ysora/stripenn ***@***.***>
Cc: Yoon, Sora ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ysora/stripenn] Stripenn score (Issue #9)


Hi Sora,

Two quick questions.

  1.  What is the starting point of each chromosome in your output? Is it 1?
  2.  Suppose the output (under 5kb) is
22 48475001 48500000 22 47775001 48500000
Is the stripe region the square formed by two points (48475001, 47775001) and (48500000, 48500000). Or (48475001, 47775001) and (48505000, 48505000)?

Thanks,
Qiuhai
